### ISSUE TITLE
4G module aansturen met jetson nano

### ISSUE THREAD

**Issue by ozi-e** [KingAbad/PEM_AutonomousCart#19]

**Comment by meto51** [comment]
nog aan het wachten voor een simkaart, ik denk dat het via m-center moet gebeuren de configuratie van de 4g-module en niet echt programmeren, tenzij je extra features erop wilt zoals automatisch sms'en versturen. dit kan ik pas uitzoeken als ik de simkaart ook echt heb.

**Comment by meto51** [comment]
https://github.com/Seeed-Studio/ublox_lara_r2_pi_hat

**Comment by meto51** [comment]
ik heb verder gezocht voor python code die alleen raspberry pi ondersteunt, maar het is in principe dezelfde chip en python code die via linux geinstalleerd moet worden. ik zal dit ook proberen of het gaat lukken.

**Comment by meto51** [comment]
dus het zal via uart verbonden moeten worden op de jetson nano en zo proberen het aan de praat te krijgen

**Comment by meto51** [comment]
https://eu-api.asm.skype.com/v1/objects/0-weu-d3-8c3b06a36514ec9044890c8d4dee377c/views/imgo

**Comment by meto51** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/48825146/97637765-8adc0600-1a3b-11eb-955b-1f863a73d1e1.png)

**Comment by meto51** [comment]
dit is een voorbeeld van hoe het op de jetson nano eruit ziet in ieder geval bij mij orange, de jetson nano leest de module zonder enige library, driver, enz. Maar het is niet kiesbaar en je kan het niet verbinden. Ik heb verder nog op de raspberry pi geprobeerd maar geeft het zelfde probleem, als je via commandline de devices gaat bekijken is het serieel wel verbonden maar je kan het niet verbinden helaas. Verder heb ik nog opgezocht en van alles uitgeprobeerd via cmd en andere instellingen maar ook helaas niet aan de praat gekregen.

**Comment by meto51** [comment]
verder dacht ik dat de probleem aan de jetson nano was omdat het niet geupdate kon worden via commando : sudo apt-get update, hij geeft een error aan. Aangeraden om de Jetson nano eens te flashen en de drivers opnieuw installeren maar helaas heb ik daar geen tijd voor gehad.

**Comment by meto51** [comment]
![Uploading WhatsApp Image 2020-10-28 at 13.13.07.jpeg…]()

**Comment by meto51** [comment]
![WhatsApp Image 2020-10-28 at 13 13 07](https://user-images.githubusercontent.com/48825146/97638404-c2977d80-1a3c-11eb-9e96-b604fdf5aa4f.jpeg)

**Comment by meto51** [comment]
![WhatsApp Image 2020-10-28 at 13 02 36](https://user-images.githubusercontent.com/48825146/97638425-caefb880-1a3c-11eb-962e-2ed5b1c1e670.jpeg)

**Comment by meto51** [comment]
via cmd de disconnected proberen aan te zetten maar het lukte helaas niet.

**Comment by meto51** [comment]
![image](https://user-images.githubusercontent.com/48825146/97638534-0a1e0980-1a3d-11eb-9653-91baa58b8223.png)

**Comment by meto51** [comment]
volgens mikroe zou het zo moeten werken...

**Comment by meto51** [comment]
er waren drivers en installs beschikbaar, maar alleen voor andere hats en shields(raspberry pi) die dezelfde lara-chip hadden. 
Veel code en voorbeelden voor de mikroe development board zelf via microbasic software die 300 euro is.

**Comment by meto51** [comment]
ik stuur nu via de 4g module deze messagem het  werkt...
